import { FC, useEffect } from 'react'
import styles from './OrderFeed.module.css';
import { FeedStatistics } from '../feed-statistics/FeedStatistics';
import { FeedItem } from '../feed-item/FeedItem';
import { TOrder } from '../../utils/types';
import { useAppSelector, useAppDispatch } from '../../services/hooks';
import { wsConnectionStart, wsConnectionDisconnect } from '../../services/actions/ws';
const OrderFeed: FC = () => {

   const ws = useAppSelector(store => store.wsAll);
   const dispatch = useAppDispatch();

   useEffect(() => {
      if(!ws.connected) {
        dispatch(wsConnectionStart("wss://norma.nomoreparties.space/orders/all"));
      }
      return () => {
         //debugger
         //dispatch(wsConnectionDisconnect());
      }
    }, [dispatch, ws.connected]);

    /*
    const orders: TOrder[] = [{
        _id: "111", 
        ingredients: [{
          "_id":"60666c42cc7b410027a1a9b1",
          "name":"Краторная булка N-200i",
          "type":"bun",
          "proteins":80,
          "fat":24,
          "carbohydrates":53,
          "calories":420,
          "price":1255,
          "image":"https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b5",
          "name":"Говяжий метеорит (отбивная)",
          "type":"main",
          "proteins":800,
          "fat":800,
          "carbohydrates":300,
          "calories":2674,
          "price":3000,
          "image":"https://code.s3.yandex.net/react/code/meat-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b6",
          "name":"Биокотлета из марсианской Магнолии",
          "type":"main",
          "proteins":420,
          "fat":142,
          "carbohydrates":242,
          "calories":4242,
          "price":424,
          "image":"https://code.s3.yandex.net/react/code/meat-01.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b7",
          "name":"Соус Spicy-X",
          "type":"sauce",
          "proteins":30,
          "fat":20,
          "carbohydrates":40,
          "calories":30,
          "price":90,
          "image":"https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b4",
          "name":"Мясо бессмертных моллюсков Protostomia",
          "type":"main",
          "proteins":433,
          "fat":244,
          "carbohydrates":33,
          "calories":420,
          "price":1337,
          "image":"https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b9",
          "name":"Соус традиционный галактический",
          "type":"sauce",
          "proteins":42,
          "fat":24,
          "carbohydrates":42,
          "calories":99,
          "price":15,
          "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b8",
          "name":"Соус фирменный Space Sauce",
          "type":"sauce",
          "proteins":50,
          "fat":22,
          "carbohydrates":11,
          "calories":14,
          "price":80,
          "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9bc",
          "name":"Плоды Фалленианского дерева",
          "type":"main",
          "proteins":20,
          "fat":5,
          "carbohydrates":55,
          "calories":77,
          "price":874,
          "image":"https://code.s3.yandex.net/react/code/sp_1.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
       }],
        owner: {
            name: "luckychel",
            email: "luckychel@yandex.ru",
            createdAt: "2024-05-14T14:00",
            updatedAt: "2024-05-14T14:00"
        },
        status: "done",
        name: "супер бургер",
        createdAt: "2024-05-14T14:00",
        updatedAt: "2024-05-14T14:00",
        number: 1231452,
        price: 882.12,
      },{
        _id: "2222", 
        ingredients: [{
          "_id":"60666c42cc7b410027a1a9b1",
          "name":"Краторная булка N-200i",
          "type":"bun",
          "proteins":80,
          "fat":24,
          "carbohydrates":53,
          "calories":420,
          "price":1255,
          "image":"https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b5",
          "name":"Говяжий метеорит (отбивная)",
          "type":"main",
          "proteins":800,
          "fat":800,
          "carbohydrates":300,
          "calories":2674,
          "price":3000,
          "image":"https://code.s3.yandex.net/react/code/meat-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b6",
          "name":"Биокотлета из марсианской Магнолии",
          "type":"main",
          "proteins":420,
          "fat":142,
          "carbohydrates":242,
          "calories":4242,
          "price":424,
          "image":"https://code.s3.yandex.net/react/code/meat-01.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b7",
          "name":"Соус Spicy-X",
          "type":"sauce",
          "proteins":30,
          "fat":20,
          "carbohydrates":40,
          "calories":30,
          "price":90,
          "image":"https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b4",
          "name":"Мясо бессмертных моллюсков Protostomia",
          "type":"main",
          "proteins":433,
          "fat":244,
          "carbohydrates":33,
          "calories":420,
          "price":1337,
          "image":"https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b9",
          "name":"Соус традиционный галактический",
          "type":"sauce",
          "proteins":42,
          "fat":24,
          "carbohydrates":42,
          "calories":99,
          "price":15,
          "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b8",
          "name":"Соус фирменный Space Sauce",
          "type":"sauce",
          "proteins":50,
          "fat":22,
          "carbohydrates":11,
          "calories":14,
          "price":80,
          "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9bc",
          "name":"Плоды Фалленианского дерева",
          "type":"main",
          "proteins":20,
          "fat":5,
          "carbohydrates":55,
          "calories":77,
          "price":874,
          "image":"https://code.s3.yandex.net/react/code/sp_1.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
       }],
        owner: {
            name: "luckychel",
            email: "luckychel@yandex.ru",
            createdAt: "2024-05-14T14:00",
            updatedAt: "2024-05-14T14:00"
        },
        status: "done",
        name: "супер бургер",
        createdAt: "2024-05-14T14:00",
        updatedAt: "2024-05-14T14:00",
        number: 89789789,
        price: 882.12,
      },
      {
        _id: "222", 
        ingredients: [{
          "_id":"60666c42cc7b410027a1a9b1",
          "name":"Краторная булка N-200i",
          "type":"bun",
          "proteins":80,
          "fat":24,
          "carbohydrates":53,
          "calories":420,
          "price":1255,
          "image":"https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b5",
          "name":"Говяжий метеорит (отбивная)",
          "type":"main",
          "proteins":800,
          "fat":800,
          "carbohydrates":300,
          "calories":2674,
          "price":3000,
          "image":"https://code.s3.yandex.net/react/code/meat-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b6",
          "name":"Биокотлета из марсианской Магнолии",
          "type":"main",
          "proteins":420,
          "fat":142,
          "carbohydrates":242,
          "calories":4242,
          "price":424,
          "image":"https://code.s3.yandex.net/react/code/meat-01.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b7",
          "name":"Соус Spicy-X",
          "type":"sauce",
          "proteins":30,
          "fat":20,
          "carbohydrates":40,
          "calories":30,
          "price":90,
          "image":"https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b4",
          "name":"Мясо бессмертных моллюсков Protostomia",
          "type":"main",
          "proteins":433,
          "fat":244,
          "carbohydrates":33,
          "calories":420,
          "price":1337,
          "image":"https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b9",
          "name":"Соус традиционный галактический",
          "type":"sauce",
          "proteins":42,
          "fat":24,
          "carbohydrates":42,
          "calories":99,
          "price":15,
          "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b8",
          "name":"Соус фирменный Space Sauce",
          "type":"sauce",
          "proteins":50,
          "fat":22,
          "carbohydrates":11,
          "calories":14,
          "price":80,
          "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9bc",
          "name":"Плоды Фалленианского дерева",
          "type":"main",
          "proteins":20,
          "fat":5,
          "carbohydrates":55,
          "calories":77,
          "price":874,
          "image":"https://code.s3.yandex.net/react/code/sp_1.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
       }],
        owner: {
            name: "luckychel",
            email: "luckychel@yandex.ru",
            createdAt: "2024-05-14T14:00",
            updatedAt: "2024-05-14T14:00"
        },
        status: "pending",
        name: "супер бургер",
        createdAt: "2024-05-14T14:00",
        updatedAt: "2024-05-14T14:00",
        number: 635634634,
        price: 882.12,
      },
      {
        _id: "333", 
        ingredients: [{
          "_id":"60666c42cc7b410027a1a9b1",
          "name":"Краторная булка N-200i",
          "type":"bun",
          "proteins":80,
          "fat":24,
          "carbohydrates":53,
          "calories":420,
          "price":1255,
          "image":"https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b5",
          "name":"Говяжий метеорит (отбивная)",
          "type":"main",
          "proteins":800,
          "fat":800,
          "carbohydrates":300,
          "calories":2674,
          "price":3000,
          "image":"https://code.s3.yandex.net/react/code/meat-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b6",
          "name":"Биокотлета из марсианской Магнолии",
          "type":"main",
          "proteins":420,
          "fat":142,
          "carbohydrates":242,
          "calories":4242,
          "price":424,
          "image":"https://code.s3.yandex.net/react/code/meat-01.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b7",
          "name":"Соус Spicy-X",
          "type":"sauce",
          "proteins":30,
          "fat":20,
          "carbohydrates":40,
          "calories":30,
          "price":90,
          "image":"https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b4",
          "name":"Мясо бессмертных моллюсков Protostomia",
          "type":"main",
          "proteins":433,
          "fat":244,
          "carbohydrates":33,
          "calories":420,
          "price":1337,
          "image":"https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b9",
          "name":"Соус традиционный галактический",
          "type":"sauce",
          "proteins":42,
          "fat":24,
          "carbohydrates":42,
          "calories":99,
          "price":15,
          "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b8",
          "name":"Соус фирменный Space Sauce",
          "type":"sauce",
          "proteins":50,
          "fat":22,
          "carbohydrates":11,
          "calories":14,
          "price":80,
          "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9bc",
          "name":"Плоды Фалленианского дерева",
          "type":"main",
          "proteins":20,
          "fat":5,
          "carbohydrates":55,
          "calories":77,
          "price":874,
          "image":"https://code.s3.yandex.net/react/code/sp_1.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
       }],
        owner: {
            name: "luckychel",
            email: "luckychel@yandex.ru",
            createdAt: "2024-05-14T14:00",
            updatedAt: "2024-05-14T14:00"
        },
        status: "pending",
        name: "супер бургер",
        createdAt: "2024-05-14T14:00",
        updatedAt: "2024-05-14T14:00",
        number: 1231452,
        price: 882.12,
      },
      {
        _id: "444", 
        ingredients: [{
          "_id":"60666c42cc7b410027a1a9b1",
          "name":"Краторная булка N-200i",
          "type":"bun",
          "proteins":80,
          "fat":24,
          "carbohydrates":53,
          "calories":420,
          "price":1255,
          "image":"https://code.s3.yandex.net/react/code/bun-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b5",
          "name":"Говяжий метеорит (отбивная)",
          "type":"main",
          "proteins":800,
          "fat":800,
          "carbohydrates":300,
          "calories":2674,
          "price":3000,
          "image":"https://code.s3.yandex.net/react/code/meat-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b6",
          "name":"Биокотлета из марсианской Магнолии",
          "type":"main",
          "proteins":420,
          "fat":142,
          "carbohydrates":242,
          "calories":4242,
          "price":424,
          "image":"https://code.s3.yandex.net/react/code/meat-01.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b7",
          "name":"Соус Spicy-X",
          "type":"sauce",
          "proteins":30,
          "fat":20,
          "carbohydrates":40,
          "calories":30,
          "price":90,
          "image":"https://code.s3.yandex.net/react/code/sauce-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b4",
          "name":"Мясо бессмертных моллюсков Protostomia",
          "type":"main",
          "proteins":433,
          "fat":244,
          "carbohydrates":33,
          "calories":420,
          "price":1337,
          "image":"https://code.s3.yandex.net/react/code/meat-02.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/meat-02-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/meat-02-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b9",
          "name":"Соус традиционный галактический",
          "type":"sauce",
          "proteins":42,
          "fat":24,
          "carbohydrates":42,
          "calories":99,
          "price":15,
          "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9b8",
          "name":"Соус фирменный Space Sauce",
          "type":"sauce",
          "proteins":50,
          "fat":22,
          "carbohydrates":11,
          "calories":14,
          "price":80,
          "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
       },
       {
          "_id":"60666c42cc7b410027a1a9bc",
          "name":"Плоды Фалленианского дерева",
          "type":"main",
          "proteins":20,
          "fat":5,
          "carbohydrates":55,
          "calories":77,
          "price":874,
          "image":"https://code.s3.yandex.net/react/code/sp_1.png",
          "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
          "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
       }],
        owner: {
            name: "luckychel",
            email: "luckychel@yandex.ru",
            createdAt: "2024-05-14T14:00",
            updatedAt: "2024-05-14T14:00"
        },
        status: "pending",
        name: "супер бургер",
        createdAt: "2024-05-14T14:00",
        updatedAt: "2024-05-14T14:00",
        number: 161241,
        price: 882.12,
      }]
   */
    return (
      
        <section className={styles.order_feed_main_content}>
            <p className={`text_type_main-large mt-10 mb-0`}>Лента заказов</p>
            <div className={styles.container}>
                <div className={`${styles.feed_list} ${'custom-scroll'}`}>
                    
                    {
                    /*orders.map((order, index) => (
                        <FeedItem data={order} key={index} />
                    ))
                    */
                    }
                    
                </div>
                <FeedStatistics />
            </div>
      </section>

    )
}
export default OrderFeed;